{% set name = "coqpit" %}
{% set version = "0.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coqpit-{{ version }}.tar.gz
  sha256: 0893c5bea8e0a4e040cedeacde1e403e894ba92778810e6ac4bb68384251f7f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - python >=3.6

test:
  imports:
    - coqpit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erogol/coqpit
  summary: Simple, light-weight config management through python data-classes.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
